/**
 * Floor A compatibility: page caching (the spec names WP Rocket/LiteSpeed;
 * WP Rocket is commercial and LiteSpeed's page cache needs a LiteSpeed
 * server, so CI automates the free, Apache-friendly WP Super Cache — the
 * paid members sit on the manual release checklist).
 *
 *   - install + activate + enable caching without fatals
 *   - a second anonymous visit is served from the page cache
 *   - the visitor color-scheme choice still works on cached pages: the
 *     cookie is read client-side by the pre-paint script, so ONE cached
 *     HTML must serve both light and dark visitors correctly
 */

const { test, expect } = require( '../e2e/fixtures' );
const { bash, collectConsoleErrors } = require( './helpers' );

test.describe( 'WP Super Cache — Floor A coexistence', () => {
	test.beforeAll( () => {
		test.setTimeout( 300_000 );
		// WP_CACHE must exist BEFORE activation — only then does WPSC's
		// activation hook lay down its dropin + config file.
		bash( 'wp config set WP_CACHE true --raw' );
		bash( 'wp plugin install wp-super-cache --activate' );
		// Activation defaults the page cache off; flip it on (simple/PHP
		// mode — no .htaccess rewrites needed).
		bash(
			`sed -i 's|$cache_enabled = false;|$cache_enabled = true;|' /var/www/html/wp-content/wp-cache-config.php`
		);
	} );

	test.afterAll( () => {
		test.setTimeout( 120_000 );
		bash(
			'wp plugin deactivate wp-super-cache && wp plugin delete wp-super-cache'
		);
		bash(
			'rm -f /var/www/html/wp-content/advanced-cache.php /var/www/html/wp-content/wp-cache-config.php && rm -rf /var/www/html/wp-content/cache'
		);
		bash( 'wp config delete WP_CACHE' );
	} );

	test( 'anonymous pages cache, and the color scheme survives caching', async ( {
		browser,
	} ) => {
		test.setTimeout( 120_000 );
		// Anonymous context: logged-in users bypass page caches.
		const context = await browser.newContext( { storageState: undefined } );
		const page = await context.newPage();
		const errors = collectConsoleErrors( page );

		// Prime the cache, then confirm the second hit is served from it.
		// (Raw body, not page.content(): WPSC's signature is an HTML comment
		// after </html>, which DOM serialization drops.)
		await page.goto( '/' );
		await expect( page.locator( '.cds--header' ) ).toBeVisible();
		const raw = await ( await page.request.get( '/' ) ).text();
		expect( raw ).toMatch( /Cached page generated by WP-Super-Cache/i );
		await page.reload();

		// Same cached HTML, dark-scheme visitor: the pre-paint script reads
		// the cookie client-side, so the page must paint dark.
		await context.addCookies( [
			{
				name: 'awt_color_scheme',
				value: 'dark',
				url: 'http://localhost:8889',
			},
		] );
		await page.reload();
		await expect( page.locator( 'body' ) ).toHaveClass( /cds--g100/ );

		// And back to light.
		await context.clearCookies( { name: 'awt_color_scheme' } );
		await page.reload();
		await expect( page.locator( 'body' ) ).not.toHaveClass( /cds--g100/ );

		expect( errors ).toEqual( [] );
		await context.close();
	} );
} );
